// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: smartcontract.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contract Management
type CreateContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnchorId      string                 `protobuf:"bytes,1,opt,name=anchorId,proto3" json:"anchorId,omitempty"`
	Suppliers     []string               `protobuf:"bytes,2,rep,name=suppliers,proto3" json:"suppliers,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	FileHash      string                 `protobuf:"bytes,4,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContractRequest) Reset() {
	*x = CreateContractRequest{}
	mi := &file_smartcontract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContractRequest) ProtoMessage() {}

func (x *CreateContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcontract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContractRequest.ProtoReflect.Descriptor instead.
func (*CreateContractRequest) Descriptor() ([]byte, []int) {
	return file_smartcontract_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContractRequest) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

func (x *CreateContractRequest) GetSuppliers() []string {
	if x != nil {
		return x.Suppliers
	}
	return nil
}

func (x *CreateContractRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateContractRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

type ApproveContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contractId,proto3" json:"contractId,omitempty"`
	SupplierId    string                 `protobuf:"bytes,2,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveContractRequest) Reset() {
	*x = ApproveContractRequest{}
	mi := &file_smartcontract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveContractRequest) ProtoMessage() {}

func (x *ApproveContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcontract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveContractRequest.ProtoReflect.Descriptor instead.
func (*ApproveContractRequest) Descriptor() ([]byte, []int) {
	return file_smartcontract_proto_rawDescGZIP(), []int{1}
}

func (x *ApproveContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ApproveContractRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

type FinalizeContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contractId,proto3" json:"contractId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeContractRequest) Reset() {
	*x = FinalizeContractRequest{}
	mi := &file_smartcontract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeContractRequest) ProtoMessage() {}

func (x *FinalizeContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcontract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeContractRequest.ProtoReflect.Descriptor instead.
func (*FinalizeContractRequest) Descriptor() ([]byte, []int) {
	return file_smartcontract_proto_rawDescGZIP(), []int{2}
}

func (x *FinalizeContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

type ContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contractId,proto3" json:"contractId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractResponse) Reset() {
	*x = ContractResponse{}
	mi := &file_smartcontract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractResponse) ProtoMessage() {}

func (x *ContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartcontract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractResponse.ProtoReflect.Descriptor instead.
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return file_smartcontract_proto_rawDescGZIP(), []int{3}
}

func (x *ContractResponse) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Token Management
type IssueTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contractId,proto3" json:"contractId,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	TotalSupply   float64                `protobuf:"fixed64,3,opt,name=totalSupply,proto3" json:"totalSupply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_smartcontract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcontract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_smartcontract_proto_rawDescGZIP(), []int{4}
}

func (x *IssueTokenRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *IssueTokenRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *IssueTokenRequest) GetTotalSupply() float64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

type TransferTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTokenRequest) Reset() {
	*x = TransferTokenRequest{}
	mi := &file_smartcontract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTokenRequest) ProtoMessage() {}

func (x *TransferTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcontract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTokenRequest.ProtoReflect.Descriptor instead.
func (*TransferTokenRequest) Descriptor() ([]byte, []int) {
	return file_smartcontract_proto_rawDescGZIP(), []int{5}
}

func (x *TransferTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TransferTokenRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferTokenRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferTokenRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SettleTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	SupplierId    string                 `protobuf:"bytes,2,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
	BankId        string                 `protobuf:"bytes,3,opt,name=bankId,proto3" json:"bankId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleTokenRequest) Reset() {
	*x = SettleTokenRequest{}
	mi := &file_smartcontract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleTokenRequest) ProtoMessage() {}

func (x *SettleTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcontract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleTokenRequest.ProtoReflect.Descriptor instead.
func (*SettleTokenRequest) Descriptor() ([]byte, []int) {
	return file_smartcontract_proto_rawDescGZIP(), []int{6}
}

func (x *SettleTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *SettleTokenRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *SettleTokenRequest) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_smartcontract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartcontract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_smartcontract_proto_rawDescGZIP(), []int{7}
}

func (x *TokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TokenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_smartcontract_proto protoreflect.FileDescriptor

const file_smartcontract_proto_rawDesc = "" +
	"\n" +
	"\x13smartcontract.proto\x12\rsmartcontract\"\x8f\x01\n" +
	"\x15CreateContractRequest\x12\x1a\n" +
	"\banchorId\x18\x01 \x01(\tR\banchorId\x12\x1c\n" +
	"\tsuppliers\x18\x02 \x03(\tR\tsuppliers\x12 \n" +
	"\vtotalAmount\x18\x03 \x01(\x01R\vtotalAmount\x12\x1a\n" +
	"\bfileHash\x18\x04 \x01(\tR\bfileHash\"X\n" +
	"\x16ApproveContractRequest\x12\x1e\n" +
	"\n" +
	"contractId\x18\x01 \x01(\tR\n" +
	"contractId\x12\x1e\n" +
	"\n" +
	"supplierId\x18\x02 \x01(\tR\n" +
	"supplierId\"9\n" +
	"\x17FinalizeContractRequest\x12\x1e\n" +
	"\n" +
	"contractId\x18\x01 \x01(\tR\n" +
	"contractId\"d\n" +
	"\x10ContractResponse\x12\x1e\n" +
	"\n" +
	"contractId\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"m\n" +
	"\x11IssueTokenRequest\x12\x1e\n" +
	"\n" +
	"contractId\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12 \n" +
	"\vtotalSupply\x18\x03 \x01(\x01R\vtotalSupply\"l\n" +
	"\x14TransferTokenRequest\x12\x18\n" +
	"\atokenId\x18\x01 \x01(\tR\atokenId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"f\n" +
	"\x12SettleTokenRequest\x12\x18\n" +
	"\atokenId\x18\x01 \x01(\tR\atokenId\x12\x1e\n" +
	"\n" +
	"supplierId\x18\x02 \x01(\tR\n" +
	"supplierId\x12\x16\n" +
	"\x06bankId\x18\x03 \x01(\tR\x06bankId\"[\n" +
	"\rTokenResponse\x12\x18\n" +
	"\atokenId\x18\x01 \x01(\tR\atokenId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x99\x04\n" +
	"\x14SmartContractService\x12W\n" +
	"\x0eCreateContract\x12$.smartcontract.CreateContractRequest\x1a\x1f.smartcontract.ContractResponse\x12Y\n" +
	"\x0fApproveContract\x12%.smartcontract.ApproveContractRequest\x1a\x1f.smartcontract.ContractResponse\x12[\n" +
	"\x10FinalizeContract\x12&.smartcontract.FinalizeContractRequest\x1a\x1f.smartcontract.ContractResponse\x12L\n" +
	"\n" +
	"IssueToken\x12 .smartcontract.IssueTokenRequest\x1a\x1c.smartcontract.TokenResponse\x12R\n" +
	"\rTransferToken\x12#.smartcontract.TransferTokenRequest\x1a\x1c.smartcontract.TokenResponse\x12N\n" +
	"\vSettleToken\x12!.smartcontract.SettleTokenRequest\x1a\x1c.smartcontract.TokenResponseB\x13Z\x11peer-anchor/protob\x06proto3"

var (
	file_smartcontract_proto_rawDescOnce sync.Once
	file_smartcontract_proto_rawDescData []byte
)

func file_smartcontract_proto_rawDescGZIP() []byte {
	file_smartcontract_proto_rawDescOnce.Do(func() {
		file_smartcontract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smartcontract_proto_rawDesc), len(file_smartcontract_proto_rawDesc)))
	})
	return file_smartcontract_proto_rawDescData
}

var file_smartcontract_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_smartcontract_proto_goTypes = []any{
	(*CreateContractRequest)(nil),   // 0: smartcontract.CreateContractRequest
	(*ApproveContractRequest)(nil),  // 1: smartcontract.ApproveContractRequest
	(*FinalizeContractRequest)(nil), // 2: smartcontract.FinalizeContractRequest
	(*ContractResponse)(nil),        // 3: smartcontract.ContractResponse
	(*IssueTokenRequest)(nil),       // 4: smartcontract.IssueTokenRequest
	(*TransferTokenRequest)(nil),    // 5: smartcontract.TransferTokenRequest
	(*SettleTokenRequest)(nil),      // 6: smartcontract.SettleTokenRequest
	(*TokenResponse)(nil),           // 7: smartcontract.TokenResponse
}
var file_smartcontract_proto_depIdxs = []int32{
	0, // 0: smartcontract.SmartContractService.CreateContract:input_type -> smartcontract.CreateContractRequest
	1, // 1: smartcontract.SmartContractService.ApproveContract:input_type -> smartcontract.ApproveContractRequest
	2, // 2: smartcontract.SmartContractService.FinalizeContract:input_type -> smartcontract.FinalizeContractRequest
	4, // 3: smartcontract.SmartContractService.IssueToken:input_type -> smartcontract.IssueTokenRequest
	5, // 4: smartcontract.SmartContractService.TransferToken:input_type -> smartcontract.TransferTokenRequest
	6, // 5: smartcontract.SmartContractService.SettleToken:input_type -> smartcontract.SettleTokenRequest
	3, // 6: smartcontract.SmartContractService.CreateContract:output_type -> smartcontract.ContractResponse
	3, // 7: smartcontract.SmartContractService.ApproveContract:output_type -> smartcontract.ContractResponse
	3, // 8: smartcontract.SmartContractService.FinalizeContract:output_type -> smartcontract.ContractResponse
	7, // 9: smartcontract.SmartContractService.IssueToken:output_type -> smartcontract.TokenResponse
	7, // 10: smartcontract.SmartContractService.TransferToken:output_type -> smartcontract.TokenResponse
	7, // 11: smartcontract.SmartContractService.SettleToken:output_type -> smartcontract.TokenResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smartcontract_proto_init() }
func file_smartcontract_proto_init() {
	if File_smartcontract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smartcontract_proto_rawDesc), len(file_smartcontract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smartcontract_proto_goTypes,
		DependencyIndexes: file_smartcontract_proto_depIdxs,
		MessageInfos:      file_smartcontract_proto_msgTypes,
	}.Build()
	File_smartcontract_proto = out.File
	file_smartcontract_proto_goTypes = nil
	file_smartcontract_proto_depIdxs = nil
}
