// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: share/smartcontract.proto

package share

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SmartContractService_CreateContract_FullMethodName   = "/smartcontract.SmartContractService/CreateContract"
	SmartContractService_ApproveContract_FullMethodName  = "/smartcontract.SmartContractService/ApproveContract"
	SmartContractService_FinalizeContract_FullMethodName = "/smartcontract.SmartContractService/FinalizeContract"
	SmartContractService_IssueToken_FullMethodName       = "/smartcontract.SmartContractService/IssueToken"
	SmartContractService_TransferToken_FullMethodName    = "/smartcontract.SmartContractService/TransferToken"
	SmartContractService_SettleToken_FullMethodName      = "/smartcontract.SmartContractService/SettleToken"
)

// SmartContractServiceClient is the client API for SmartContractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartContractServiceClient interface {
	CreateContract(ctx context.Context, in *CreateContractRequest, opts ...grpc.CallOption) (*ContractResponse, error)
	ApproveContract(ctx context.Context, in *ApproveContractRequest, opts ...grpc.CallOption) (*ContractResponse, error)
	FinalizeContract(ctx context.Context, in *FinalizeContractRequest, opts ...grpc.CallOption) (*ContractResponse, error)
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	TransferToken(ctx context.Context, in *TransferTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	SettleToken(ctx context.Context, in *SettleTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type smartContractServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartContractServiceClient(cc grpc.ClientConnInterface) SmartContractServiceClient {
	return &smartContractServiceClient{cc}
}

func (c *smartContractServiceClient) CreateContract(ctx context.Context, in *CreateContractRequest, opts ...grpc.CallOption) (*ContractResponse, error) {
	out := new(ContractResponse)
	err := c.cc.Invoke(ctx, SmartContractService_CreateContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractServiceClient) ApproveContract(ctx context.Context, in *ApproveContractRequest, opts ...grpc.CallOption) (*ContractResponse, error) {
	out := new(ContractResponse)
	err := c.cc.Invoke(ctx, SmartContractService_ApproveContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractServiceClient) FinalizeContract(ctx context.Context, in *FinalizeContractRequest, opts ...grpc.CallOption) (*ContractResponse, error) {
	out := new(ContractResponse)
	err := c.cc.Invoke(ctx, SmartContractService_FinalizeContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractServiceClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, SmartContractService_IssueToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractServiceClient) TransferToken(ctx context.Context, in *TransferTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, SmartContractService_TransferToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractServiceClient) SettleToken(ctx context.Context, in *SettleTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, SmartContractService_SettleToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartContractServiceServer is the server API for SmartContractService service.
// All implementations must embed UnimplementedSmartContractServiceServer
// for forward compatibility
type SmartContractServiceServer interface {
	CreateContract(context.Context, *CreateContractRequest) (*ContractResponse, error)
	ApproveContract(context.Context, *ApproveContractRequest) (*ContractResponse, error)
	FinalizeContract(context.Context, *FinalizeContractRequest) (*ContractResponse, error)
	IssueToken(context.Context, *IssueTokenRequest) (*TokenResponse, error)
	TransferToken(context.Context, *TransferTokenRequest) (*TokenResponse, error)
	SettleToken(context.Context, *SettleTokenRequest) (*TokenResponse, error)
	mustEmbedUnimplementedSmartContractServiceServer()
}

// UnimplementedSmartContractServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSmartContractServiceServer struct {
}

func (UnimplementedSmartContractServiceServer) CreateContract(context.Context, *CreateContractRequest) (*ContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContract not implemented")
}
func (UnimplementedSmartContractServiceServer) ApproveContract(context.Context, *ApproveContractRequest) (*ContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveContract not implemented")
}
func (UnimplementedSmartContractServiceServer) FinalizeContract(context.Context, *FinalizeContractRequest) (*ContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeContract not implemented")
}
func (UnimplementedSmartContractServiceServer) IssueToken(context.Context, *IssueTokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedSmartContractServiceServer) TransferToken(context.Context, *TransferTokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferToken not implemented")
}
func (UnimplementedSmartContractServiceServer) SettleToken(context.Context, *SettleTokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleToken not implemented")
}
func (UnimplementedSmartContractServiceServer) mustEmbedUnimplementedSmartContractServiceServer() {}

// UnsafeSmartContractServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartContractServiceServer will
// result in compilation errors.
type UnsafeSmartContractServiceServer interface {
	mustEmbedUnimplementedSmartContractServiceServer()
}

func RegisterSmartContractServiceServer(s grpc.ServiceRegistrar, srv SmartContractServiceServer) {
	s.RegisterService(&SmartContractService_ServiceDesc, srv)
}

func _SmartContractService_CreateContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractServiceServer).CreateContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractService_CreateContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractServiceServer).CreateContract(ctx, req.(*CreateContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractService_ApproveContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractServiceServer).ApproveContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractService_ApproveContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractServiceServer).ApproveContract(ctx, req.(*ApproveContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractService_FinalizeContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractServiceServer).FinalizeContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractService_FinalizeContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractServiceServer).FinalizeContract(ctx, req.(*FinalizeContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractService_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractServiceServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractService_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractServiceServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractService_TransferToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractServiceServer).TransferToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractService_TransferToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractServiceServer).TransferToken(ctx, req.(*TransferTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractService_SettleToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractServiceServer).SettleToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractService_SettleToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractServiceServer).SettleToken(ctx, req.(*SettleTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartContractService_ServiceDesc is the grpc.ServiceDesc for SmartContractService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartContractService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartcontract.SmartContractService",
	HandlerType: (*SmartContractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContract",
			Handler:    _SmartContractService_CreateContract_Handler,
		},
		{
			MethodName: "ApproveContract",
			Handler:    _SmartContractService_ApproveContract_Handler,
		},
		{
			MethodName: "FinalizeContract",
			Handler:    _SmartContractService_FinalizeContract_Handler,
		},
		{
			MethodName: "IssueToken",
			Handler:    _SmartContractService_IssueToken_Handler,
		},
		{
			MethodName: "TransferToken",
			Handler:    _SmartContractService_TransferToken_Handler,
		},
		{
			MethodName: "SettleToken",
			Handler:    _SmartContractService_SettleToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "share/smartcontract.proto",
}
