version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - blockchain-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=blockchain
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=example
    depends_on:
      - mongo
      - ms-blockchain
    networks:
      - blockchain-network

  ms-blockchain:
    build: ./ms-blockchain
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/blockchain?authSource=admin
    depends_on:
      - mongo
    networks:
      - blockchain-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: blockchain
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongodb:/data/db
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge