apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: blockchain-production
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: blockchain
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
