apiVersion: v1
kind: Service
metadata:
  name: peer-supplier
  namespace: blockchain-production
  labels:
    app.kubernetes.io/name: blockchain-peer
    app.kubernetes.io/component: peer
    app.kubernetes.io/part-of: blockchain
    peer-type: supplier
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    name: http
  - port: 9093
    targetPort: 9093
    name: grpc
  - port: 9095
    targetPort: 9095
    name: metrics
  selector:
    app.kubernetes.io/name: blockchain-peer
    app.kubernetes.io/component: peer
    peer-type: supplier
