apiVersion: v1
kind: Service
metadata:
  name: peer-main-bank
  namespace: blockchain-production
  labels:
    app.kubernetes.io/name: blockchain-peer
    app.kubernetes.io/component: peer
    app.kubernetes.io/part-of: blockchain
    peer-type: main-bank
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    name: http
  - port: 9092
    targetPort: 9092
    name: grpc
  - port: 9094
    targetPort: 9094
    name: metrics
  selector:
    app.kubernetes.io/name: blockchain-peer
    app.kubernetes.io/component: peer
    peer-type: main-bank
