// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: blockchain.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height       int64             `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transactions []*Transaction     `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	PreviousHash string            `protobuf:"bytes,4,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	Hash         string            `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	MerkleRoot   string            `protobuf:"bytes,6,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Signatures   []*BlockSignature `protobuf:"bytes,7,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Block) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *Block) GetSignatures() []*BlockSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type BlockSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrdererId string `protobuf:"bytes,1,opt,name=orderer_id,json=ordererId,proto3" json:"orderer_id,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *BlockSignature) Reset() {
	*x = BlockSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSignature) ProtoMessage() {}

func (x *BlockSignature) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BlockSignature) GetOrdererId() string {
	if x != nil {
		return x.OrdererId
	}
	return ""
}

func (x *BlockSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BlockSignature) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId   string               `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionType string               `protobuf:"bytes,2,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	ContractId      string               `protobuf:"bytes,3,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	TokenId         string               `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	SenderId        string               `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId      string               `protobuf:"bytes,6,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Amount          float64              `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Payload         string               `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *Transaction) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Transaction) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *Transaction) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Transaction) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type PrePrepareMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View           string `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	SequenceNumber string `protobuf:"bytes,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Block          *Block `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	Digest         string `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
}

func (x *PrePrepareMessage) Reset() {
	*x = PrePrepareMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrePrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMessage) ProtoMessage() {}

func (x *PrePrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PrepareMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View           string `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	SequenceNumber string `protobuf:"bytes,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	OrdererId      string `protobuf:"bytes,4,opt,name=orderer_id,json=ordererId,proto3" json:"orderer_id,omitempty"`
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CommitMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View           string `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	SequenceNumber string `protobuf:"bytes,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	OrdererId      string `protobuf:"bytes,4,opt,name=orderer_id,json=ordererId,proto3" json:"orderer_id,omitempty"`
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConsensusMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are assignable to Message:
	//	*ConsensusMessage_PrePrepare
	//	*ConsensusMessage_Prepare
	//	*ConsensusMessage_Commit
	Message isConsensusMessage_Message `protobuf_oneof:"message"`
}

type isConsensusMessage_Message interface {
	isConsensusMessage_Message()
}

type ConsensusMessage_PrePrepare struct {
	PrePrepare *PrePrepareMessage `protobuf:"bytes,2,opt,name=pre_prepare,json=prePrepare,proto3,oneof"`
}

type ConsensusMessage_Prepare struct {
	Prepare *PrepareMessage `protobuf:"bytes,3,opt,name=prepare,proto3,oneof"`
}

type ConsensusMessage_Commit struct {
	Commit *CommitMessage `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

func (x *ConsensusMessage) Reset() {
	*x = ConsensusMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessage) ProtoMessage() {}

func (x *ConsensusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsensusMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConsensusMessage) GetMessage() isConsensusMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ConsensusMessage) GetPrePrepare() *PrePrepareMessage {
	if x, ok := x.GetMessage().(*ConsensusMessage_PrePrepare); ok {
		return x.PrePrepare
	}
	return nil
}

func (x *ConsensusMessage) GetPrepare() *PrepareMessage {
	if x, ok := x.GetMessage().(*ConsensusMessage_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (x *ConsensusMessage) GetCommit() *CommitMessage {
	if x, ok := x.GetMessage().(*ConsensusMessage_Commit); ok {
		return x.Commit
	}
	return nil
}

type ConsensusMessage_PrePrepare struct {
	PrePrepare *PrePrepareMessage `protobuf:"bytes,2,opt,name=pre_prepare,json=prePrepare,proto3,oneof"`
}

type ConsensusMessage_Prepare struct {
	Prepare *PrepareMessage `protobuf:"bytes,3,opt,name=prepare,proto3,oneof"`
}

type ConsensusMessage_Commit struct {
	Commit *CommitMessage `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

func (*ConsensusMessage_PrePrepare) isConsensusMessage_Message() {}

func (*ConsensusMessage_Prepare) isConsensusMessage_Message() {}

func (*ConsensusMessage_Commit) isConsensusMessage_Message() {}

type SubmitTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId      string       `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *SubmitTxRequest) Reset() {
	*x = SubmitTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxRequest) ProtoMessage() {}

func (x *SubmitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SubmitTxReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success       bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SubmitTxReply) Reset() {
	*x = SubmitTxReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTxReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxReply) ProtoMessage() {}

func (x *SubmitTxReply) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StreamBlocksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId     string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	StartHeight int64  `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
}

func (x *StreamBlocksRequest) Reset() {
	*x = StreamBlocksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBlocksRequest) ProtoMessage() {}

func (x *StreamBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AckReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AckReply) Reset() {
	*x = AckReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReply) ProtoMessage() {}

func (x *AckReply) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Minimal protobuf descriptor and service definitions
var File_blockchain_proto protoreflect.FileDescriptor

var file_blockchain_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e,
}

var file_blockchain_proto_rawDescGZIP = protoimpl.X.CompressGZIP(file_blockchain_proto_rawDesc)

var file_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_blockchain_proto_goTypes = []interface{}{
	(*Block)(nil),               // 0: blockchain.Block
	(*BlockSignature)(nil),      // 1: blockchain.BlockSignature
	(*Transaction)(nil),         // 2: blockchain.Transaction
	(*PrePrepareMessage)(nil),   // 3: blockchain.PrePrepareMessage
	(*PrepareMessage)(nil),      // 4: blockchain.PrepareMessage
	(*CommitMessage)(nil),       // 5: blockchain.CommitMessage
	(*ConsensusMessage)(nil),    // 6: blockchain.ConsensusMessage
	(*SubmitTxRequest)(nil),     // 7: blockchain.SubmitTxRequest
	(*SubmitTxReply)(nil),       // 8: blockchain.SubmitTxReply
	(*StreamBlocksRequest)(nil), // 9: blockchain.StreamBlocksRequest
	(*AckReply)(nil),            // 10: blockchain.AckReply
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_blockchain_proto_depIdxs = []int32{
	11, // 0: blockchain.Block.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 1: blockchain.Block.transactions:type_name -> blockchain.Transaction
	1,  // 2: blockchain.Block.signatures:type_name -> blockchain.BlockSignature
	11, // 3: blockchain.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 4: blockchain.PrePrepareMessage.block:type_name -> blockchain.Block
	3,  // 5: blockchain.ConsensusMessage.pre_prepare:type_name -> blockchain.PrePrepareMessage
	4,  // 6: blockchain.ConsensusMessage.prepare:type_name -> blockchain.PrepareMessage
	5,  // 7: blockchain.ConsensusMessage.commit:type_name -> blockchain.CommitMessage
	2,  // 8: blockchain.SubmitTxRequest.transaction:type_name -> blockchain.Transaction
	7,  // 9: blockchain.OrdererService.SubmitTx:input_type -> blockchain.SubmitTxRequest
	9,  // 10: blockchain.OrdererService.StreamBlocks:input_type -> blockchain.StreamBlocksRequest
	6,  // 11: blockchain.OrdererService.Consensus:input_type -> blockchain.ConsensusMessage
	8,  // 12: blockchain.OrdererService.SubmitTx:output_type -> blockchain.SubmitTxReply
	0,  // 13: blockchain.OrdererService.StreamBlocks:output_type -> blockchain.Block
	10, // 14: blockchain.OrdererService.Consensus:output_type -> blockchain.AckReply
	12, // [12:15] is the sub-list for method outputs
	9,  // [9:12] is the sub-list for method inputs
	9,  // [9:9] is the sub-list for extensions
	0,  // [0:9] is the sub-list for extensions
}

func init() { file_blockchain_proto_init() }
func file_blockchain_proto_init() {
	if File_blockchain_proto != nil {
		return
	}
	file_blockchain_proto_initOnce.Do(func() {
		type x struct{}
		out := protoimpl.TypeBuilder{
			File: protoimpl.DescBuilder{
				GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
				RawDescriptor: file_blockchain_proto_rawDesc,
				NumEnums:      0,
				NumMessages:   11,
				NumExtensions: 0,
				NumServices:   1,
			},
			GoTypes:           file_blockchain_proto_goTypes,
			DependencyIndexes: file_blockchain_proto_depIdxs,
			MessageInfos:      file_blockchain_proto_msgTypes,
		}.Build()
		File_blockchain_proto = out.File
		file_blockchain_proto_rawDesc = nil
		file_blockchain_proto_goTypes = nil
		file_blockchain_proto_depIdxs = nil
	})
}

// Minimal gRPC service interface
type UnimplementedOrdererServiceServer struct{}

func (UnimplementedOrdererServiceServer) SubmitTx(context.Context, *SubmitTxRequest) (*SubmitTxReply, error) {
	return nil, fmt.Errorf("method SubmitTx not implemented")
}

func (UnimplementedOrdererServiceServer) StreamBlocks(*StreamBlocksRequest, OrdererService_StreamBlocksServer) error {
	return fmt.Errorf("method StreamBlocks not implemented")
}

func (UnimplementedOrdererServiceServer) Consensus(context.Context, *ConsensusMessage) (*AckReply, error) {
	return nil, fmt.Errorf("method Consensus not implemented")
}

type OrdererServiceServer interface {
	SubmitTx(context.Context, *SubmitTxRequest) (*SubmitTxReply, error)
	StreamBlocks(*StreamBlocksRequest, OrdererService_StreamBlocksServer) error
	Consensus(context.Context, *ConsensusMessage) (*AckReply, error)
}

type OrdererService_StreamBlocksServer interface {
	Send(*Block) error
	Context() context.Context
}

var file_blockchain_proto_initOnce sync.Once