// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: blockchain.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OrdererService_SubmitTx_FullMethodName     = "/blockchain.OrdererService/SubmitTx"
	OrdererService_StreamBlocks_FullMethodName = "/blockchain.OrdererService/StreamBlocks"
	OrdererService_Consensus_FullMethodName    = "/blockchain.OrdererService/Consensus"
)

// OrdererServiceClient is the client API for OrdererService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrdererServiceClient interface {
	SubmitTx(ctx context.Context, in *SubmitTxRequest, opts ...grpc.CallOption) (*SubmitTxReply, error)
	StreamBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (OrdererService_StreamBlocksClient, error)
	Consensus(ctx context.Context, in *ConsensusMessage, opts ...grpc.CallOption) (*AckReply, error)
}

type ordererServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdererServiceClient(cc grpc.ClientConnInterface) OrdererServiceClient {
	return &ordererServiceClient{cc}
}

func (c *ordererServiceClient) SubmitTx(ctx context.Context, in *SubmitTxRequest, opts ...grpc.CallOption) (*SubmitTxReply, error) {
	out := new(SubmitTxReply)
	err := c.cc.Invoke(ctx, OrdererService_SubmitTx_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererServiceClient) StreamBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (OrdererService_StreamBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &OrdererService_ServiceDesc.Streams[0], OrdererService_StreamBlocks_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &ordererServiceStreamBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrdererService_StreamBlocksClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type ordererServiceStreamBlocksClient struct {
	grpc.ClientStream
}

func (x *ordererServiceStreamBlocksClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ordererServiceClient) Consensus(ctx context.Context, in *ConsensusMessage, opts ...grpc.CallOption) (*AckReply, error) {
	out := new(AckReply)
	err := c.cc.Invoke(ctx, OrdererService_Consensus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdererServiceServer is the server API for OrdererService service.
// All implementations must embed UnimplementedOrdererServiceServer
// for forward compatibility
type OrdererServiceServer interface {
	SubmitTx(context.Context, *SubmitTxRequest) (*SubmitTxReply, error)
	StreamBlocks(*StreamBlocksRequest, OrdererService_StreamBlocksServer) error
	Consensus(context.Context, *ConsensusMessage) (*AckReply, error)
	mustEmbedUnimplementedOrdererServiceServer()
}

// UnimplementedOrdererServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrdererServiceServer struct {
}

func (UnimplementedOrdererServiceServer) SubmitTx(context.Context, *SubmitTxRequest) (*SubmitTxReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTx not implemented")
}
func (UnimplementedOrdererServiceServer) StreamBlocks(*StreamBlocksRequest, OrdererService_StreamBlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamBlocks not implemented")
}
func (UnimplementedOrdererServiceServer) Consensus(context.Context, *ConsensusMessage) (*AckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consensus not implemented")
}
func (UnimplementedOrdererServiceServer) mustEmbedUnimplementedOrdererServiceServer() {}

// UnsafeOrdererServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdererServiceServer will
// result in compilation errors.
type UnsafeOrdererServiceServer interface {
	mustEmbedUnimplementedOrdererServiceServer()
}

func RegisterOrdererServiceServer(s grpc.ServiceRegistrar, srv OrdererServiceServer) {
	s.RegisterService(&OrdererService_ServiceDesc, srv)
}

func _OrdererService_SubmitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServiceServer).SubmitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdererService_SubmitTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServiceServer).SubmitTx(ctx, req.(*SubmitTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdererService_StreamBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrdererServiceServer).StreamBlocks(m, &ordererServiceStreamBlocksServer{stream})
}

type OrdererService_StreamBlocksServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type ordererServiceStreamBlocksServer struct {
	grpc.ServerStream
}

func (x *ordererServiceStreamBlocksServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

func _OrdererService_Consensus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsensusMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServiceServer).Consensus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdererService_Consensus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServiceServer).Consensus(ctx, req.(*ConsensusMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// OrdererService_ServiceDesc is the grpc.ServiceDesc for OrdererService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrdererService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.OrdererService",
	HandlerType: (*OrdererServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTx",
			Handler:    _OrdererService_SubmitTx_Handler,
		},
		{
			MethodName: "Consensus",
			Handler:    _OrdererService_Consensus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBlocks",
			Handler:       _OrdererService_StreamBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blockchain.proto",
}
