// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: blockchain.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block represents a blockchain block with PBFT signatures
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	PreviousHash  string                 `protobuf:"bytes,4,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,6,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Signatures    []*BlockSignature      `protobuf:"bytes,7,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_blockchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *Block) GetSignatures() []*BlockSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// BlockSignature represents a PBFT signature from an orderer
type BlockSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrdererId     string                 `protobuf:"bytes,1,opt,name=orderer_id,json=ordererId,proto3" json:"orderer_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSignature) Reset() {
	*x = BlockSignature{}
	mi := &file_blockchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSignature) ProtoMessage() {}

func (x *BlockSignature) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSignature.ProtoReflect.Descriptor instead.
func (*BlockSignature) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *BlockSignature) GetOrdererId() string {
	if x != nil {
		return x.OrdererId
	}
	return ""
}

func (x *BlockSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BlockSignature) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// Transaction represents a blockchain transaction
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionType string                 `protobuf:"bytes,2,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	ContractId      string                 `protobuf:"bytes,3,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	TokenId         string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId      string                 `protobuf:"bytes,6,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Payload         string                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_blockchain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *Transaction) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Transaction) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *Transaction) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Transaction) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Consensus message types for PBFT
type PrePrepareMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	View           string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	SequenceNumber string                 `protobuf:"bytes,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Block          *Block                 `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	Digest         string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrePrepareMessage) Reset() {
	*x = PrePrepareMessage{}
	mi := &file_blockchain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMessage) ProtoMessage() {}

func (x *PrePrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareMessage.ProtoReflect.Descriptor instead.
func (*PrePrepareMessage) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{3}
}

func (x *PrePrepareMessage) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *PrePrepareMessage) GetSequenceNumber() string {
	if x != nil {
		return x.SequenceNumber
	}
	return ""
}

func (x *PrePrepareMessage) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *PrePrepareMessage) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type PrepareMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	View           string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	SequenceNumber string                 `protobuf:"bytes,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	OrdererId      string                 `protobuf:"bytes,4,opt,name=orderer_id,json=ordererId,proto3" json:"orderer_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_blockchain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareMessage) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *PrepareMessage) GetSequenceNumber() string {
	if x != nil {
		return x.SequenceNumber
	}
	return ""
}

func (x *PrepareMessage) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PrepareMessage) GetOrdererId() string {
	if x != nil {
		return x.OrdererId
	}
	return ""
}

type CommitMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	View           string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	SequenceNumber string                 `protobuf:"bytes,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	OrdererId      string                 `protobuf:"bytes,4,opt,name=orderer_id,json=ordererId,proto3" json:"orderer_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	mi := &file_blockchain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessage.ProtoReflect.Descriptor instead.
func (*CommitMessage) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{5}
}

func (x *CommitMessage) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *CommitMessage) GetSequenceNumber() string {
	if x != nil {
		return x.SequenceNumber
	}
	return ""
}

func (x *CommitMessage) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *CommitMessage) GetOrdererId() string {
	if x != nil {
		return x.OrdererId
	}
	return ""
}

type ConsensusMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // PRE_PREPARE, PREPARE, COMMIT
	// Types that are valid to be assigned to Message:
	//
	//	*ConsensusMessage_PrePrepare
	//	*ConsensusMessage_Prepare
	//	*ConsensusMessage_Commit
	Message       isConsensusMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessage) Reset() {
	*x = ConsensusMessage{}
	mi := &file_blockchain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessage) ProtoMessage() {}

func (x *ConsensusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessage.ProtoReflect.Descriptor instead.
func (*ConsensusMessage) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{6}
}

func (x *ConsensusMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConsensusMessage) GetMessage() isConsensusMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ConsensusMessage) GetPrePrepare() *PrePrepareMessage {
	if x != nil {
		if x, ok := x.Message.(*ConsensusMessage_PrePrepare); ok {
			return x.PrePrepare
		}
	}
	return nil
}

func (x *ConsensusMessage) GetPrepare() *PrepareMessage {
	if x != nil {
		if x, ok := x.Message.(*ConsensusMessage_Prepare); ok {
			return x.Prepare
		}
	}
	return nil
}

func (x *ConsensusMessage) GetCommit() *CommitMessage {
	if x != nil {
		if x, ok := x.Message.(*ConsensusMessage_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

type isConsensusMessage_Message interface {
	isConsensusMessage_Message()
}

type ConsensusMessage_PrePrepare struct {
	PrePrepare *PrePrepareMessage `protobuf:"bytes,2,opt,name=pre_prepare,json=prePrepare,proto3,oneof"`
}

type ConsensusMessage_Prepare struct {
	Prepare *PrepareMessage `protobuf:"bytes,3,opt,name=prepare,proto3,oneof"`
}

type ConsensusMessage_Commit struct {
	Commit *CommitMessage `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

func (*ConsensusMessage_PrePrepare) isConsensusMessage_Message() {}

func (*ConsensusMessage_Prepare) isConsensusMessage_Message() {}

func (*ConsensusMessage_Commit) isConsensusMessage_Message() {}

// Orderer service messages
type SubmitTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxRequest) Reset() {
	*x = SubmitTxRequest{}
	mi := &file_blockchain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxRequest) ProtoMessage() {}

func (x *SubmitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxRequest.ProtoReflect.Descriptor instead.
func (*SubmitTxRequest) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitTxRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SubmitTxRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SubmitTxReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxReply) Reset() {
	*x = SubmitTxReply{}
	mi := &file_blockchain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxReply) ProtoMessage() {}

func (x *SubmitTxReply) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxReply.ProtoReflect.Descriptor instead.
func (*SubmitTxReply) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitTxReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitTxReply) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SubmitTxReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	StartHeight   int64                  `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"` // optional: start from specific height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBlocksRequest) Reset() {
	*x = StreamBlocksRequest{}
	mi := &file_blockchain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBlocksRequest) ProtoMessage() {}

func (x *StreamBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBlocksRequest.ProtoReflect.Descriptor instead.
func (*StreamBlocksRequest) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{9}
}

func (x *StreamBlocksRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *StreamBlocksRequest) GetStartHeight() int64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

type AckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckReply) Reset() {
	*x = AckReply{}
	mi := &file_blockchain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReply) ProtoMessage() {}

func (x *AckReply) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckReply.ProtoReflect.Descriptor instead.
func (*AckReply) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{10}
}

func (x *AckReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_blockchain_proto protoreflect.FileDescriptor

const file_blockchain_proto_rawDesc = "" +
	"\n" +
	"\x10blockchain.proto\x12\n" +
	"blockchain\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xac\x02\n" +
	"\x05Block\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12;\n" +
	"\ftransactions\x18\x03 \x03(\v2\x17.blockchain.TransactionR\ftransactions\x12#\n" +
	"\rprevious_hash\x18\x04 \x01(\tR\fpreviousHash\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x1f\n" +
	"\vmerkle_root\x18\x06 \x01(\tR\n" +
	"merkleRoot\x12:\n" +
	"\n" +
	"signatures\x18\a \x03(\v2\x1a.blockchain.BlockSignatureR\n" +
	"signatures\"l\n" +
	"\x0eBlockSignature\x12\x1d\n" +
	"\n" +
	"orderer_id\x18\x01 \x01(\tR\tordererId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"\xc5\x02\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12)\n" +
	"\x10transaction_type\x18\x02 \x01(\tR\x0ftransactionType\x12\x1f\n" +
	"\vcontract_id\x18\x03 \x01(\tR\n" +
	"contractId\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x06 \x01(\tR\n" +
	"receiverId\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x18\n" +
	"\apayload\x18\b \x01(\tR\apayload\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x91\x01\n" +
	"\x11PrePrepareMessage\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\tR\x0esequenceNumber\x12'\n" +
	"\x05block\x18\x03 \x01(\v2\x11.blockchain.BlockR\x05block\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"\x84\x01\n" +
	"\x0ePrepareMessage\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\tR\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"orderer_id\x18\x04 \x01(\tR\tordererId\"\x83\x01\n" +
	"\rCommitMessage\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\tR\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"orderer_id\x18\x04 \x01(\tR\tordererId\"\xe0\x01\n" +
	"\x10ConsensusMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12@\n" +
	"\vpre_prepare\x18\x02 \x01(\v2\x1d.blockchain.PrePrepareMessageH\x00R\n" +
	"prePrepare\x126\n" +
	"\aprepare\x18\x03 \x01(\v2\x1a.blockchain.PrepareMessageH\x00R\aprepare\x123\n" +
	"\x06commit\x18\x04 \x01(\v2\x19.blockchain.CommitMessageH\x00R\x06commitB\t\n" +
	"\amessage\"e\n" +
	"\x0fSubmitTxRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x129\n" +
	"\vtransaction\x18\x02 \x01(\v2\x17.blockchain.TransactionR\vtransaction\"j\n" +
	"\rSubmitTxReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Q\n" +
	"\x13StreamBlocksRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12!\n" +
	"\fstart_height\x18\x02 \x01(\x03R\vstartHeight\">\n" +
	"\bAckReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xdb\x01\n" +
	"\x0eOrdererService\x12B\n" +
	"\bSubmitTx\x12\x1b.blockchain.SubmitTxRequest\x1a\x19.blockchain.SubmitTxReply\x12D\n" +
	"\fStreamBlocks\x12\x1f.blockchain.StreamBlocksRequest\x1a\x11.blockchain.Block0\x01\x12?\n" +
	"\tConsensus\x12\x1c.blockchain.ConsensusMessage\x1a\x14.blockchain.AckReplyB\x0eZ\fshared/protob\x06proto3"

var (
	file_blockchain_proto_rawDescOnce sync.Once
	file_blockchain_proto_rawDescData []byte
)

func file_blockchain_proto_rawDescGZIP() []byte {
	file_blockchain_proto_rawDescOnce.Do(func() {
		file_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_proto_rawDesc), len(file_blockchain_proto_rawDesc)))
	})
	return file_blockchain_proto_rawDescData
}

var file_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_blockchain_proto_goTypes = []any{
	(*Block)(nil),                 // 0: blockchain.Block
	(*BlockSignature)(nil),        // 1: blockchain.BlockSignature
	(*Transaction)(nil),           // 2: blockchain.Transaction
	(*PrePrepareMessage)(nil),     // 3: blockchain.PrePrepareMessage
	(*PrepareMessage)(nil),        // 4: blockchain.PrepareMessage
	(*CommitMessage)(nil),         // 5: blockchain.CommitMessage
	(*ConsensusMessage)(nil),      // 6: blockchain.ConsensusMessage
	(*SubmitTxRequest)(nil),       // 7: blockchain.SubmitTxRequest
	(*SubmitTxReply)(nil),         // 8: blockchain.SubmitTxReply
	(*StreamBlocksRequest)(nil),   // 9: blockchain.StreamBlocksRequest
	(*AckReply)(nil),              // 10: blockchain.AckReply
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_blockchain_proto_depIdxs = []int32{
	11, // 0: blockchain.Block.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 1: blockchain.Block.transactions:type_name -> blockchain.Transaction
	1,  // 2: blockchain.Block.signatures:type_name -> blockchain.BlockSignature
	11, // 3: blockchain.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 4: blockchain.PrePrepareMessage.block:type_name -> blockchain.Block
	3,  // 5: blockchain.ConsensusMessage.pre_prepare:type_name -> blockchain.PrePrepareMessage
	4,  // 6: blockchain.ConsensusMessage.prepare:type_name -> blockchain.PrepareMessage
	5,  // 7: blockchain.ConsensusMessage.commit:type_name -> blockchain.CommitMessage
	2,  // 8: blockchain.SubmitTxRequest.transaction:type_name -> blockchain.Transaction
	7,  // 9: blockchain.OrdererService.SubmitTx:input_type -> blockchain.SubmitTxRequest
	9,  // 10: blockchain.OrdererService.StreamBlocks:input_type -> blockchain.StreamBlocksRequest
	6,  // 11: blockchain.OrdererService.Consensus:input_type -> blockchain.ConsensusMessage
	8,  // 12: blockchain.OrdererService.SubmitTx:output_type -> blockchain.SubmitTxReply
	0,  // 13: blockchain.OrdererService.StreamBlocks:output_type -> blockchain.Block
	10, // 14: blockchain.OrdererService.Consensus:output_type -> blockchain.AckReply
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_blockchain_proto_init() }
func file_blockchain_proto_init() {
	if File_blockchain_proto != nil {
		return
	}
	file_blockchain_proto_msgTypes[6].OneofWrappers = []any{
		(*ConsensusMessage_PrePrepare)(nil),
		(*ConsensusMessage_Prepare)(nil),
		(*ConsensusMessage_Commit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_proto_rawDesc), len(file_blockchain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blockchain_proto_goTypes,
		DependencyIndexes: file_blockchain_proto_depIdxs,
		MessageInfos:      file_blockchain_proto_msgTypes,
	}.Build()
	File_blockchain_proto = out.File
	file_blockchain_proto_goTypes = nil
	file_blockchain_proto_depIdxs = nil
}
