server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: blockchain
      username: root
      password: example
  main:
    allow-bean-definition-overriding: true

blockchain:
  url: http://ms-blockchain:8081

logging:
  level:
    org.springframework.security: DEBUG
    com.example.blockchain: DEBUG