// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/blockchain_gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockchainGateway_SubmitTransaction_FullMethodName    = "/blockchain_gateway.BlockchainGateway/SubmitTransaction"
	BlockchainGateway_GetTransactionStatus_FullMethodName = "/blockchain_gateway.BlockchainGateway/GetTransactionStatus"
)

// BlockchainGatewayClient is the client API for BlockchainGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Blockchain Gateway Service
type BlockchainGatewayClient interface {
	// Submit transaction proposal to peers for endorsement
	SubmitTransaction(ctx context.Context, in *TransactionProposal, opts ...grpc.CallOption) (*TransactionResponse, error)
	// Get transaction status
	GetTransactionStatus(ctx context.Context, in *TransactionStatusRequest, opts ...grpc.CallOption) (*TransactionStatusResponse, error)
}

type blockchainGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainGatewayClient(cc grpc.ClientConnInterface) BlockchainGatewayClient {
	return &blockchainGatewayClient{cc}
}

func (c *blockchainGatewayClient) SubmitTransaction(ctx context.Context, in *TransactionProposal, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, BlockchainGateway_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainGatewayClient) GetTransactionStatus(ctx context.Context, in *TransactionStatusRequest, opts ...grpc.CallOption) (*TransactionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionStatusResponse)
	err := c.cc.Invoke(ctx, BlockchainGateway_GetTransactionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainGatewayServer is the server API for BlockchainGateway service.
// All implementations must embed UnimplementedBlockchainGatewayServer
// for forward compatibility.
//
// Blockchain Gateway Service
type BlockchainGatewayServer interface {
	// Submit transaction proposal to peers for endorsement
	SubmitTransaction(context.Context, *TransactionProposal) (*TransactionResponse, error)
	// Get transaction status
	GetTransactionStatus(context.Context, *TransactionStatusRequest) (*TransactionStatusResponse, error)
	mustEmbedUnimplementedBlockchainGatewayServer()
}

// UnimplementedBlockchainGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockchainGatewayServer struct{}

func (UnimplementedBlockchainGatewayServer) SubmitTransaction(context.Context, *TransactionProposal) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedBlockchainGatewayServer) GetTransactionStatus(context.Context, *TransactionStatusRequest) (*TransactionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionStatus not implemented")
}
func (UnimplementedBlockchainGatewayServer) mustEmbedUnimplementedBlockchainGatewayServer() {}
func (UnimplementedBlockchainGatewayServer) testEmbeddedByValue()                           {}

// UnsafeBlockchainGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainGatewayServer will
// result in compilation errors.
type UnsafeBlockchainGatewayServer interface {
	mustEmbedUnimplementedBlockchainGatewayServer()
}

func RegisterBlockchainGatewayServer(s grpc.ServiceRegistrar, srv BlockchainGatewayServer) {
	// If the following call pancis, it indicates UnimplementedBlockchainGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockchainGateway_ServiceDesc, srv)
}

func _BlockchainGateway_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainGatewayServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainGateway_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainGatewayServer).SubmitTransaction(ctx, req.(*TransactionProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainGateway_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainGatewayServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainGateway_GetTransactionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainGatewayServer).GetTransactionStatus(ctx, req.(*TransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockchainGateway_ServiceDesc is the grpc.ServiceDesc for BlockchainGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain_gateway.BlockchainGateway",
	HandlerType: (*BlockchainGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _BlockchainGateway_SubmitTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _BlockchainGateway_GetTransactionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blockchain_gateway.proto",
}

const (
	PeerEndorsement_EvaluateProposal_FullMethodName = "/blockchain_gateway.PeerEndorsement/EvaluateProposal"
)

// PeerEndorsementClient is the client API for PeerEndorsement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Peer Endorsement Service
type PeerEndorsementClient interface {
	// Evaluate proposal and return endorsement
	EvaluateProposal(ctx context.Context, in *ProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
}

type peerEndorsementClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerEndorsementClient(cc grpc.ClientConnInterface) PeerEndorsementClient {
	return &peerEndorsementClient{cc}
}

func (c *peerEndorsementClient) EvaluateProposal(ctx context.Context, in *ProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, PeerEndorsement_EvaluateProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerEndorsementServer is the server API for PeerEndorsement service.
// All implementations must embed UnimplementedPeerEndorsementServer
// for forward compatibility.
//
// Peer Endorsement Service
type PeerEndorsementServer interface {
	// Evaluate proposal and return endorsement
	EvaluateProposal(context.Context, *ProposalRequest) (*ProposalResponse, error)
	mustEmbedUnimplementedPeerEndorsementServer()
}

// UnimplementedPeerEndorsementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerEndorsementServer struct{}

func (UnimplementedPeerEndorsementServer) EvaluateProposal(context.Context, *ProposalRequest) (*ProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateProposal not implemented")
}
func (UnimplementedPeerEndorsementServer) mustEmbedUnimplementedPeerEndorsementServer() {}
func (UnimplementedPeerEndorsementServer) testEmbeddedByValue()                         {}

// UnsafePeerEndorsementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerEndorsementServer will
// result in compilation errors.
type UnsafePeerEndorsementServer interface {
	mustEmbedUnimplementedPeerEndorsementServer()
}

func RegisterPeerEndorsementServer(s grpc.ServiceRegistrar, srv PeerEndorsementServer) {
	// If the following call pancis, it indicates UnimplementedPeerEndorsementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerEndorsement_ServiceDesc, srv)
}

func _PeerEndorsement_EvaluateProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerEndorsementServer).EvaluateProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerEndorsement_EvaluateProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerEndorsementServer).EvaluateProposal(ctx, req.(*ProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerEndorsement_ServiceDesc is the grpc.ServiceDesc for PeerEndorsement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerEndorsement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain_gateway.PeerEndorsement",
	HandlerType: (*PeerEndorsementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateProposal",
			Handler:    _PeerEndorsement_EvaluateProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blockchain_gateway.proto",
}
