// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/blockchain_gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction Proposal from API Gateway
type TransactionProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChaincodeName string                 `protobuf:"bytes,5,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionProposal) Reset() {
	*x = TransactionProposal{}
	mi := &file_proto_blockchain_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionProposal) ProtoMessage() {}

func (x *TransactionProposal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionProposal.ProtoReflect.Descriptor instead.
func (*TransactionProposal) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionProposal) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionProposal) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *TransactionProposal) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TransactionProposal) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *TransactionProposal) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

// Endorsement from Peer
type Endorsement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Signature       []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	RwSet           *ReadWriteSet          `protobuf:"bytes,3,opt,name=rw_set,json=rwSet,proto3" json:"rw_set,omitempty"`
	ResponseStatus  int32                  `protobuf:"varint,4,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,5,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Endorsement) Reset() {
	*x = Endorsement{}
	mi := &file_proto_blockchain_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endorsement) ProtoMessage() {}

func (x *Endorsement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endorsement.ProtoReflect.Descriptor instead.
func (*Endorsement) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Endorsement) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Endorsement) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Endorsement) GetRwSet() *ReadWriteSet {
	if x != nil {
		return x.RwSet
	}
	return nil
}

func (x *Endorsement) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *Endorsement) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

// Read-Write Set
type ReadWriteSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadKeys      []string               `protobuf:"bytes,1,rep,name=read_keys,json=readKeys,proto3" json:"read_keys,omitempty"`
	WriteSet      map[string]string      `protobuf:"bytes,2,rep,name=write_set,json=writeSet,proto3" json:"write_set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWriteSet) Reset() {
	*x = ReadWriteSet{}
	mi := &file_proto_blockchain_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWriteSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteSet) ProtoMessage() {}

func (x *ReadWriteSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteSet.ProtoReflect.Descriptor instead.
func (*ReadWriteSet) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ReadWriteSet) GetReadKeys() []string {
	if x != nil {
		return x.ReadKeys
	}
	return nil
}

func (x *ReadWriteSet) GetWriteSet() map[string]string {
	if x != nil {
		return x.WriteSet
	}
	return nil
}

// Transaction Response
type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	BlockNumber   string                 `protobuf:"bytes,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Endorsements  []*Endorsement         `protobuf:"bytes,5,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_proto_blockchain_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionResponse) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *TransactionResponse) GetEndorsements() []*Endorsement {
	if x != nil {
		return x.Endorsements
	}
	return nil
}

// Transaction Status Request
type TransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatusRequest) Reset() {
	*x = TransactionStatusRequest{}
	mi := &file_proto_blockchain_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusRequest) ProtoMessage() {}

func (x *TransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*TransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// Transaction Status Response
type TransactionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // PENDING, COMMITTED, FAILED
	BlockNumber   string                 `protobuf:"bytes,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatusResponse) Reset() {
	*x = TransactionStatusResponse{}
	mi := &file_proto_blockchain_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusResponse) ProtoMessage() {}

func (x *TransactionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusResponse.ProtoReflect.Descriptor instead.
func (*TransactionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionStatusResponse) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *TransactionStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Proposal Request to Peer
type ProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChaincodeName string                 `protobuf:"bytes,5,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalRequest) Reset() {
	*x = ProposalRequest{}
	mi := &file_proto_blockchain_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalRequest) ProtoMessage() {}

func (x *ProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalRequest.ProtoReflect.Descriptor instead.
func (*ProposalRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ProposalRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProposalRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ProposalRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProposalRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ProposalRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

// Proposal Response from Peer
type ProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RwSet         *ReadWriteSet          `protobuf:"bytes,4,opt,name=rw_set,json=rwSet,proto3" json:"rw_set,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	PeerId        string                 `protobuf:"bytes,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalResponse) Reset() {
	*x = ProposalResponse{}
	mi := &file_proto_blockchain_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalResponse) ProtoMessage() {}

func (x *ProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalResponse.ProtoReflect.Descriptor instead.
func (*ProposalResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ProposalResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProposalResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProposalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProposalResponse) GetRwSet() *ReadWriteSet {
	if x != nil {
		return x.RwSet
	}
	return nil
}

func (x *ProposalResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ProposalResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

var File_proto_blockchain_gateway_proto protoreflect.FileDescriptor

const file_proto_blockchain_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/blockchain_gateway.proto\x12\x12blockchain_gateway\"\xbb\x01\n" +
	"\x13TransactionProposal\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12%\n" +
	"\x0echaincode_name\x18\x05 \x01(\tR\rchaincodeName\"\xd1\x01\n" +
	"\vEndorsement\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x127\n" +
	"\x06rw_set\x18\x03 \x01(\v2 .blockchain_gateway.ReadWriteSetR\x05rwSet\x12'\n" +
	"\x0fresponse_status\x18\x04 \x01(\x05R\x0eresponseStatus\x12)\n" +
	"\x10response_message\x18\x05 \x01(\tR\x0fresponseMessage\"\xb5\x01\n" +
	"\fReadWriteSet\x12\x1b\n" +
	"\tread_keys\x18\x01 \x03(\tR\breadKeys\x12K\n" +
	"\twrite_set\x18\x02 \x03(\v2..blockchain_gateway.ReadWriteSet.WriteSetEntryR\bwriteSet\x1a;\n" +
	"\rWriteSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\x13TransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\fblock_number\x18\x04 \x01(\tR\vblockNumber\x12C\n" +
	"\fendorsements\x18\x05 \x03(\v2\x1f.blockchain_gateway.EndorsementR\fendorsements\"A\n" +
	"\x18TransactionStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\xa2\x01\n" +
	"\x19TransactionStatusResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fblock_number\x18\x03 \x01(\tR\vblockNumber\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xb7\x01\n" +
	"\x0fProposalRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12%\n" +
	"\x0echaincode_name\x18\x05 \x01(\tR\rchaincodeName\"\xdb\x01\n" +
	"\x10ProposalResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x127\n" +
	"\x06rw_set\x18\x04 \x01(\v2 .blockchain_gateway.ReadWriteSetR\x05rwSet\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\tR\x06peerId2\xef\x01\n" +
	"\x11BlockchainGateway\x12e\n" +
	"\x11SubmitTransaction\x12'.blockchain_gateway.TransactionProposal\x1a'.blockchain_gateway.TransactionResponse\x12s\n" +
	"\x14GetTransactionStatus\x12,.blockchain_gateway.TransactionStatusRequest\x1a-.blockchain_gateway.TransactionStatusResponse2p\n" +
	"\x0fPeerEndorsement\x12]\n" +
	"\x10EvaluateProposal\x12#.blockchain_gateway.ProposalRequest\x1a$.blockchain_gateway.ProposalResponseB\x15Z\x13blockchain-gw/protob\x06proto3"

var (
	file_proto_blockchain_gateway_proto_rawDescOnce sync.Once
	file_proto_blockchain_gateway_proto_rawDescData []byte
)

func file_proto_blockchain_gateway_proto_rawDescGZIP() []byte {
	file_proto_blockchain_gateway_proto_rawDescOnce.Do(func() {
		file_proto_blockchain_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blockchain_gateway_proto_rawDesc), len(file_proto_blockchain_gateway_proto_rawDesc)))
	})
	return file_proto_blockchain_gateway_proto_rawDescData
}

var file_proto_blockchain_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_blockchain_gateway_proto_goTypes = []any{
	(*TransactionProposal)(nil),       // 0: blockchain_gateway.TransactionProposal
	(*Endorsement)(nil),               // 1: blockchain_gateway.Endorsement
	(*ReadWriteSet)(nil),              // 2: blockchain_gateway.ReadWriteSet
	(*TransactionResponse)(nil),       // 3: blockchain_gateway.TransactionResponse
	(*TransactionStatusRequest)(nil),  // 4: blockchain_gateway.TransactionStatusRequest
	(*TransactionStatusResponse)(nil), // 5: blockchain_gateway.TransactionStatusResponse
	(*ProposalRequest)(nil),           // 6: blockchain_gateway.ProposalRequest
	(*ProposalResponse)(nil),          // 7: blockchain_gateway.ProposalResponse
	nil,                               // 8: blockchain_gateway.ReadWriteSet.WriteSetEntry
}
var file_proto_blockchain_gateway_proto_depIdxs = []int32{
	2, // 0: blockchain_gateway.Endorsement.rw_set:type_name -> blockchain_gateway.ReadWriteSet
	8, // 1: blockchain_gateway.ReadWriteSet.write_set:type_name -> blockchain_gateway.ReadWriteSet.WriteSetEntry
	1, // 2: blockchain_gateway.TransactionResponse.endorsements:type_name -> blockchain_gateway.Endorsement
	2, // 3: blockchain_gateway.ProposalResponse.rw_set:type_name -> blockchain_gateway.ReadWriteSet
	0, // 4: blockchain_gateway.BlockchainGateway.SubmitTransaction:input_type -> blockchain_gateway.TransactionProposal
	4, // 5: blockchain_gateway.BlockchainGateway.GetTransactionStatus:input_type -> blockchain_gateway.TransactionStatusRequest
	6, // 6: blockchain_gateway.PeerEndorsement.EvaluateProposal:input_type -> blockchain_gateway.ProposalRequest
	3, // 7: blockchain_gateway.BlockchainGateway.SubmitTransaction:output_type -> blockchain_gateway.TransactionResponse
	5, // 8: blockchain_gateway.BlockchainGateway.GetTransactionStatus:output_type -> blockchain_gateway.TransactionStatusResponse
	7, // 9: blockchain_gateway.PeerEndorsement.EvaluateProposal:output_type -> blockchain_gateway.ProposalResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_blockchain_gateway_proto_init() }
func file_proto_blockchain_gateway_proto_init() {
	if File_proto_blockchain_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blockchain_gateway_proto_rawDesc), len(file_proto_blockchain_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_blockchain_gateway_proto_goTypes,
		DependencyIndexes: file_proto_blockchain_gateway_proto_depIdxs,
		MessageInfos:      file_proto_blockchain_gateway_proto_msgTypes,
	}.Build()
	File_proto_blockchain_gateway_proto = out.File
	file_proto_blockchain_gateway_proto_goTypes = nil
	file_proto_blockchain_gateway_proto_depIdxs = nil
}
