// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/peer_endorsement.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proposal Request to Peer
type ProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChaincodeName string                 `protobuf:"bytes,5,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalRequest) Reset() {
	*x = ProposalRequest{}
	mi := &file_proto_peer_endorsement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalRequest) ProtoMessage() {}

func (x *ProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_endorsement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalRequest.ProtoReflect.Descriptor instead.
func (*ProposalRequest) Descriptor() ([]byte, []int) {
	return file_proto_peer_endorsement_proto_rawDescGZIP(), []int{0}
}

func (x *ProposalRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProposalRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ProposalRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProposalRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ProposalRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

// Proposal Response from Peer
type ProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RwSet         *ReadWriteSet          `protobuf:"bytes,4,opt,name=rw_set,json=rwSet,proto3" json:"rw_set,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	PeerId        string                 `protobuf:"bytes,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalResponse) Reset() {
	*x = ProposalResponse{}
	mi := &file_proto_peer_endorsement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalResponse) ProtoMessage() {}

func (x *ProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_endorsement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalResponse.ProtoReflect.Descriptor instead.
func (*ProposalResponse) Descriptor() ([]byte, []int) {
	return file_proto_peer_endorsement_proto_rawDescGZIP(), []int{1}
}

func (x *ProposalResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProposalResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProposalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProposalResponse) GetRwSet() *ReadWriteSet {
	if x != nil {
		return x.RwSet
	}
	return nil
}

func (x *ProposalResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ProposalResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// Read-Write Set
type ReadWriteSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadKeys      []string               `protobuf:"bytes,1,rep,name=read_keys,json=readKeys,proto3" json:"read_keys,omitempty"`
	WriteSet      map[string]string      `protobuf:"bytes,2,rep,name=write_set,json=writeSet,proto3" json:"write_set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWriteSet) Reset() {
	*x = ReadWriteSet{}
	mi := &file_proto_peer_endorsement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWriteSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteSet) ProtoMessage() {}

func (x *ReadWriteSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_endorsement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteSet.ProtoReflect.Descriptor instead.
func (*ReadWriteSet) Descriptor() ([]byte, []int) {
	return file_proto_peer_endorsement_proto_rawDescGZIP(), []int{2}
}

func (x *ReadWriteSet) GetReadKeys() []string {
	if x != nil {
		return x.ReadKeys
	}
	return nil
}

func (x *ReadWriteSet) GetWriteSet() map[string]string {
	if x != nil {
		return x.WriteSet
	}
	return nil
}

var File_proto_peer_endorsement_proto protoreflect.FileDescriptor

const file_proto_peer_endorsement_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/peer_endorsement.proto\x12\x10peer_endorsement\"\xb7\x01\n" +
	"\x0fProposalRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12%\n" +
	"\x0echaincode_name\x18\x05 \x01(\tR\rchaincodeName\"\xd9\x01\n" +
	"\x10ProposalResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x125\n" +
	"\x06rw_set\x18\x04 \x01(\v2\x1e.peer_endorsement.ReadWriteSetR\x05rwSet\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\tR\x06peerId\"\xb3\x01\n" +
	"\fReadWriteSet\x12\x1b\n" +
	"\tread_keys\x18\x01 \x03(\tR\breadKeys\x12I\n" +
	"\twrite_set\x18\x02 \x03(\v2,.peer_endorsement.ReadWriteSet.WriteSetEntryR\bwriteSet\x1a;\n" +
	"\rWriteSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012l\n" +
	"\x0fPeerEndorsement\x12Y\n" +
	"\x10EvaluateProposal\x12!.peer_endorsement.ProposalRequest\x1a\".peer_endorsement.ProposalResponseB\x13Z\x11peer-anchor/protob\x06proto3"

var (
	file_proto_peer_endorsement_proto_rawDescOnce sync.Once
	file_proto_peer_endorsement_proto_rawDescData []byte
)

func file_proto_peer_endorsement_proto_rawDescGZIP() []byte {
	file_proto_peer_endorsement_proto_rawDescOnce.Do(func() {
		file_proto_peer_endorsement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_peer_endorsement_proto_rawDesc), len(file_proto_peer_endorsement_proto_rawDesc)))
	})
	return file_proto_peer_endorsement_proto_rawDescData
}

var file_proto_peer_endorsement_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_peer_endorsement_proto_goTypes = []any{
	(*ProposalRequest)(nil),  // 0: peer_endorsement.ProposalRequest
	(*ProposalResponse)(nil), // 1: peer_endorsement.ProposalResponse
	(*ReadWriteSet)(nil),     // 2: peer_endorsement.ReadWriteSet
	nil,                      // 3: peer_endorsement.ReadWriteSet.WriteSetEntry
}
var file_proto_peer_endorsement_proto_depIdxs = []int32{
	2, // 0: peer_endorsement.ProposalResponse.rw_set:type_name -> peer_endorsement.ReadWriteSet
	3, // 1: peer_endorsement.ReadWriteSet.write_set:type_name -> peer_endorsement.ReadWriteSet.WriteSetEntry
	0, // 2: peer_endorsement.PeerEndorsement.EvaluateProposal:input_type -> peer_endorsement.ProposalRequest
	1, // 3: peer_endorsement.PeerEndorsement.EvaluateProposal:output_type -> peer_endorsement.ProposalResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_peer_endorsement_proto_init() }
func file_proto_peer_endorsement_proto_init() {
	if File_proto_peer_endorsement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_peer_endorsement_proto_rawDesc), len(file_proto_peer_endorsement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_peer_endorsement_proto_goTypes,
		DependencyIndexes: file_proto_peer_endorsement_proto_depIdxs,
		MessageInfos:      file_proto_peer_endorsement_proto_msgTypes,
	}.Build()
	File_proto_peer_endorsement_proto = out.File
	file_proto_peer_endorsement_proto_goTypes = nil
	file_proto_peer_endorsement_proto_depIdxs = nil
}
